### ISSUE TITLE
where is the cmgui's source code?

### ISSUE THREAD

**Issue by taopanpan** [ABI-Software-Laboratory/ICMA#1]

**Comment by Jagirhussan** [comment]
You can find the latest version of cmgui library (OpenCMISS ZINC) here http://physiomeproject.org/software/opencmiss/zinc

However, the api has changed significantly and you may not be able to build ICMA code against it.

**Comment by Jagirhussan** [comment]
You can find a cmgui code version against which the ICMA code was built at https://sourceforge.net/p/cardiacatlas/captovtk/ci/default/tree/cmissnoitk/
