### ISSUE TITLE
No "widgets" module

### ISSUE THREAD

**Issue by jaffamd** [ABI-Software-Laboratory/ICMA#2]
While attempting to run the Python-based GUI version of ICMA 2.0, I get the following error:
`ImportError: No module named icma.widgets`
I think I ran all the appropriate steps to install the dependencies, but there don't appear to be any resources out there to learn how to use this system...

**Comment by Jagirhussan** [comment]
Ensure that PYTHONPATH is set correctly. i.e python is able to find the icma module folder. The above error often occurs when the bat/bash script is run from a different directory.
