### ISSUE TITLE
No module _context 

### ISSUE THREAD

**Issue by dijbi** [ABI-Software-Laboratory/ICMA#3]
Hi,

I did follow the steps in the README.
After launching the .bat,  i have an error with a unrecognized module
Here are the logs: 
```
Traceback (most recent call last):
  File "C:\Users\***\Miniconda3\lib\site-packages\zinc-3.1.1_amd64_windows_python_3.6-py3.6.egg\opencmiss\zinc\context.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\***\Miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "icma\ICMA.py", line 46, in <module>
    from icma.widgets import ICMAMain, WorkspaceWidget, LogConsole, Disclaimer
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\icma\widgets.py", line 46, in <module>
    from viewers.VTKWidgets import DicomCollageViewer, SpeckleTrackingWindow
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\viewers\VTKWidgets.py", line 51, in <module>
    from speckleTracking.TrackAndView import TrackAndView
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\speckleTracking\TrackAndView.py", line 39, in <module>
    from capmodel.LV import Heart
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\capmodel\LV.py", line 37, in <module>
    from opencmiss.zinc.context import Context
  File "C:\Users\***\Miniconda3\lib\site-packages\zinc-3.1.1_amd64_windows_python_3.6-py3.6.egg\opencmiss\zinc\context.py", line 17, in <module>
    _context = swig_import_helper()
  File "C:\Users\***\Miniconda3\lib\site-packages\zinc-3.1.1_amd64_windows_python_3.6-py3.6.egg\opencmiss\zinc\context.py", line 16, in swig_import_helper
    return importlib.import_module('_context')
  File "C:\Users\***\Miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_context'

```
Context.py, _context.pyd are in the right directory : C:\Users\***\Miniconda3\lib\site-packages\zinc-3.1.1_amd64_windows_python_3.6-py3.6.egg\opencmiss\zinc

Any help for the next step to follow ?
Thks

- W10
- Python 3.6
- Miniconda 3

**Comment by Jagirhussan** [comment]
Could you check if you have installed opencmiss-zinc stack correctly. It appears that python is not able to load the corresponding dll's.
Pre built libraries for Opencmiss-zinc can be downloaded from http://opencmiss.org/downloads.html#/package/opencmisslibs/download

Once you have installed it, ensure you can load it by starting a python shell and check if the following import statement works
from opencmiss.zinc.context import Context

**Comment by dijbi** [comment]
Hello,

thanks à lot. I had already downloaded the prebuilt binary.
After adding manually the path to my system path, there was no import problem with _context. 👍 

What stucks me now is Elementfieldtemplate from opencmiss.zinc 

`  File "icma\ICMA.py", line 46, in <module>
    from icma.widgets import ICMAMain, WorkspaceWidget, LogConsole, Disclaimer
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\icma\widgets.py", line 47, in <module>
    from meshing.zincMeshGenerator import ICMAMeshGenerator
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\meshing\zincMeshGenerator.py", line 39, in <module>
    from opencmiss.zinc.element import Element, Elementbasis, Elementfieldtemplate
ImportError: cannot import name 'Elementfieldtemplate'`

I can easily import **Element** & **ElementBasis** from a python prompt, but not **Elementfieldtemplate**.
Any suggestions ?

Thanks again

**Comment by Jagirhussan** [comment]
Could you check the version of opencmiss-zinc that has been installed. You can find this using the following commands
import opencmiss.zinc
print opencmiss.zinc.__version__

**Comment by dijbi** [comment]
Hi

`import opencmiss.zinc
print opencmiss.zinc.version`

throws an error that statesthat opencmiss.zinc has no version attribute
`AttributeError: module 'opencmiss.zinc' has no attribute 'version'`

BYT, import opencmiss.zinc throws no error
`print(opencmiss.zinc)` gives me 
 `<module 'opencmiss.zinc' from 'C:\\Program Files\\OpenCMISS Libraries SDK\\lib\\python3.6\\Release\\opencmiss.zinc\\opencmiss\\zinc\\__init__.py'>`

From the [OpenCmiss website](http://opencmiss.org/downloads.html#/package/opencmisslibs/download), the version downloaded is Version: 1.3.0, for Windows

Thxs for the help !

**Comment by rchristie** [comment]
Try the latest development release (it’s a good idea to use it anyway):

http://opencmiss.org/downloads.html#/package/opencmisslibs/devreleases

BTW If the following works, then a version of zinc is installed:
from opencmiss.zinc.context import Context

I’m not sure that version code you wrote should work; after the above command enter:
context = Context('test')
print(context.getVersionString())

The above uses the print() syntax for Python 3. Beware that Python 2 is being deprecated – by Python – in the next few months, and we’ll follow suit.

cheers,
Richard

**Comment by dijbi** [comment]
Hooray, i did launch the software. Thanks a lot @rchristie 👍 👍 

FYI, i used the dev version: 1.3.0.20171204225554, the last one (Version: 1.3.0.20180309013242) did not work either. 

I tried w/ 2 examples from 2 differents  ultrasound machines, that gives two differents errors.

1) Phillips Cx50 : the INFO output from the Log windows shows :
`2019-03-20 19:55:53,644 - INFO - Parsing local DICOMDIR C:/Users/djibi/Dev/ICMA/t/*****/DICOMDIR 
2019-03-20 19:55:53,644 - INFO - DICOMFileDirectory: Creating DICOM directory from C:/Users/djibi/Dev/ICMA/t/*****/DICOMDIR
2019-03-20 19:55:53,872 - INFO - DICOMFileDirectory: Parsing of DICOMDIR completed
2019-03-20 19:55:53,952 - INFO - Retrieved 0 patients 
2019-03-20 19:55:53,952 - INFO - Updating Patients Model`

2) Siemens Acusson SC2000 : the app crashes. 

Output from the command line print :
`Traceback (most recent call last):
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\dicomio\DirectoryManager.py", line 460, in run
    self.parserDICOMDIR(dicomDir,os.path.dirname(self.dicomdir))
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\dicomio\DirectoryManager.py", line 583, in parserDICOMDIR
    pname = value.split('^')
AttributeError: 'PersonName3' object has no attribute 'split'`

Any solution why it's not loading ?
Does anyone has some US DICOM examples i could use to test ?

**Comment by Jagirhussan** [comment]
Hi,
   Thanks for the observations and report.
The issues are related pydicom's inability (under python 3) to deal with compressed dicom data. The other option you have is to revert to python 2.7 where this does not occur.

**Comment by dijbi** [comment]
Hi 
Thanks for the answer

i decided to revert to python 2.7.
i can not get to make the app work, i have now a VTK error.

`Traceback (most recent call last):
  File "icma\ICMA.py", line 46, in <module>
    from icma.widgets import ICMAMain, WorkspaceWidget, LogConsole, Disclaimer
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\icma\widgets.py", line 46, in <module>
    from viewers.VTKWidgets import DicomCollageViewer, SpeckleTrackingWindow
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\viewers\VTKWidgets.py", line 49, in <module>
    from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
  File "C:\Users\****\Miniconda2\lib\site-packages\vtk\qt\QVTKRenderWindowInteractor.py", line 36, in <module>
    import Qt
ImportError: No module named Qt`

**Conda list (for packages versions under Miniconda 2**
`
-  Name                    Version                   Build  Channel
- asn1crypto                0.24.0                   py27_0
- backports                 1.0                      py27_1
- backports.functools_lru_cache 1.5                      py27_1
- backports_abc             0.5              py27h6d9a788_0
- blas                      1.0                         mkl
- bzip2                     1.0.6                h0c8e037_5
- ca-certificates           2019.1.23                     0
- certifi                   2019.3.9                 py27_0
- cffi                      1.12.2           py27hcfb25f9_1
- chardet                   3.0.4                    py27_1
- conda                     4.6.8                    py27_0
- conda-env                 2.6.0                         1
- console_shortcut          0.1.1                         3
- cryptography              2.4.2            py27hc64555f_0
- cryptography-vectors      2.6.1                      py_0
- curl                      7.62.0               h7a46e7a_0
- cycler                    0.10.0           py27h0308610_0
- diskcache                 3.1.1                      py_0    conda-forge
- enum34                    1.1.6                    py27_1
- expat                     2.2.5                h2880e7c_0
- freetype                  2.9.1                h4d385ea_1
- functools32               3.2.3.2                  py27_1
- future                    0.17.1                   py27_0
- futures                   3.2.0                    py27_0
- hdf4                      4.2.12                    vc9_0
- hdf5                      1.10.4               h530792d_0
- icc_rt                    2019.0.0             h0cc432a_1
- icu                       57.1                      vc9_0
- idna                      2.8                      py27_0
- intel-openmp              2019.3                      203
- ipaddress                 1.0.22                   py27_0
- jpeg                      8d                        vc9_2
- jsoncpp                   1.8.3             vc9h6a32881_0
- kiwisolver                1.0.1            py27hc56fc5f_0
- krb5                      1.13.2                        0
- libcurl                   7.62.0               h7a46e7a_0
- libiconv                  1.15                 h9278755_7
- libnetcdf                 4.3.3.1                   vc9_4
- libpng                    1.6.36               h7a46e7a_0
- libssh2                   1.8.0                         1    conda-forge
- libtiff                   4.0.6                     vc9_2
- libxml2                   2.9.9                h325896a_0
- lz4-c                     1.8.1.2              h3cc03e0_0
- matplotlib                2.2.3            py27h263d877_0
- menuinst                  1.4.16           py27h0c8e037_0
- mkl                       2019.3                      203
- mkl_fft                   1.0.10           py27h44c1dab_0
- msvc_runtime              1.0.1                     vc9_0
- numpy                     1.11.3          py27h239e66a_12
- numpy-base                1.11.3          py27hb1d0314_12
- olefile                   0.46                     py27_0
- openssl                   1.0.2r               h0c8e037_0
- pandas                    0.23.4           py27h39f3610_0
- pillow                    3.0.0                    py27_0
- pip                       19.0.3                   py27_0
- pycosat                   0.6.3            py27h0c8e037_0
- pycparser                 2.19                     py27_0
- pydicom                   1.2.2                      py_0    conda-forge
- pyopenssl                 19.0.0                   py27_0
- pyparsing                 2.3.1                    py27_0
- pyqt                      5.6.0            py27hc56fc5f_6
- pysocks                   1.6.8                    py27_0
- python                    2.7.14              h4a10d90_31
- python-dateutil           2.8.0                    py27_0
- pytz                      2018.9                   py27_0
- pywin32                   223              py27h0c8e037_1
- qt                        5.6.2                     vc9_0
- requests                  2.21.0                   py27_0
- ruamel_yaml               0.15.46          py27h0c8e037_0
- scipy                     1.2.1            py27h4c3ab11_0
- setuptools                40.8.0                   py27_0
- singledispatch            3.4.0.3          py27h18657b7_0
- sip                       4.18.1           py27hc56fc5f_2
- six                       1.12.0                   py27_0
- sqlite                    3.27.2               h0c8e037_0
- tbb                       2019.4               hdc96acc_0
- tk                        8.5.18                    vc9_0
- tornado                   5.1.1            py27h0c8e037_0
- urllib3                   1.24.1                   py27_0
- vc                        9                    h7299396_1
- vs2008_runtime            9.00.30729.1         hfaea7d5_1
- vs2015_runtime            14.15.26706          h3a45250_0
- vtk                       5.10.1                   py27_0
- wheel                     0.33.1                   py27_0
- win_inet_pton             1.1.0                    py27_0
- wincertstore              0.2              py27h87a2792_0
- xlsxwriter                1.1.5                    py27_0
- xz                        5.2.4                h3cc03e0_4
- yaml                      0.1.7                h00170ee_2
- zlib                      1.2.11               h3cc03e0_3
- zstd                      1.3.7                h1b0e4d7_0

Link to Opencmiss via PYTHONPATH (unchanged version  1.3.0.20171204225554).

Could you print the version you have w/ your working ICMA ?
Thx !

**Comment by dijbi** [comment]
Update :
Seems to  be a PyQt 4 vs 5 import problem.
I change directly inside the QVTKRenderWindowInteractor.py file to force tje use of PyQt5 with a _qt_ alias not to mess up too much the code.
(`from PyQt5 import Qt as qt`)
-- not a good thing to mess up the code but the error is not showing up anymore

Run into the opencmiss.zinc link error (with _context not being recognized), albeit the path inside PYTHONPATH being correct, albeit loading without error the opencmiss.zinc...

**Comment by dijbi** [comment]
For people interested in using ICMA w/ Python 2.7, here are my notes  (to be completed) :

- if you use Miniconda, make sure that Python 2.7 is in 64 bits (import error of _Context is the first error to show) -- this is mandatory for Opencmiss.
-  to bind Opencmiss with Python 2.7, you have to download the ZIP (not the installer) which has Python 2.7 bindings. .... you can do `python setup.py install` on it (see ICMA Readme)
- you have to add the packages : scikit-image,  PySide
- Minimum version of VTK is 7.1.0 (VTK under Miniconda w/ P2.7 is 6.3.0)-- > VTK 7.1.1 is available on channel conda forge so `conda install -c conda-forge vtk=7.1.1`

**Comment by dijbi** [comment]
I not loosing faith....

Here is the log :
`Traceback (most recent call last):
  File "icma\ICMA.py", line 88, in <module>
    QtWidgets.QMessageBox.critical(app, "Required module missing", "VTK Python release 7.1.0 or higher is required!! Install or contact your administrator")
TypeError: critical(QWidget, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'QApplication'`

I have both VTK with Miniconda (version 6.3.0) and i have installed the VTK 7.1.1 with the standalone installer (https://vtk.org/download/). I added the PATH of the vtk python library to PYTHONPATH.

How to make ICMA understand to pick inside the VTK 7.1.1. version ?
If i remove the vtk from Miniconda, i have a no module name error

`  File "icma\ICMA.py", line 46, in <module>
    from icma.widgets import ICMAMain, WorkspaceWidget, LogConsole, Disclaimer
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\icma\widgets.py", line 46, in <module>
    from viewers.VTKWidgets import DicomCollageViewer, SpeckleTrackingWindow
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\viewers\VTKWidgets.py", line 40, in <module>
    import os, vtk, numpy, logging, tempfile
ImportError: No module named vtk`

**Comment by dijbi** [comment]
I am not loosing faith.... yet

I have PyQt5 installed, but an error is still thrown :
`(base) C:\Program Files\ICMA-master\Python\ICMA2.0>python icma\ICMA.py
Traceback (most recent call last):
  File "icma\ICMA.py", line 46, in <module>
    from icma.widgets import ICMAMain, WorkspaceWidget, LogConsole, Disclaimer
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\icma\widgets.py", line 46, in <module>
    from viewers.VTKWidgets import DicomCollageViewer, SpeckleTrackingWindow
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\viewers\VTKWidgets.py", line 49, in <module>
    from vtk.qt4.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
  File "C:\Users\****\Miniconda2\lib\site-packages\vtk\qt4\QVTKRenderWindowInteractor.py", line 11, in <module>
    raise ImportError("Cannot load either PyQt or PySide")
ImportError: Cannot load either PyQt or PySide`


Under the python bash, i can load PyQt5 but not _pyqt_
When i tried to install PySide, the app launches but an error is still thrown :


`(base) C:\Program Files\ICMA-master\Python\ICMA2.0>python icma\ICMA.py
QObject::connect: Cannot queue arguments of type 'QTextBlock'
(Make sure 'QTextBlock' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
Traceback (most recent call last):
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\viewers\VTKWidgets.py", line 707, in setupUi
    iv = MultiFrameDicomViewer(ddm)
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\viewers\VTKWidgets.py", line 303, in __init__
    self.setupUi(self)
  File "C:\Program Files\ICMA-master\Python\ICMA2.0\viewers\VTKWidgets.py", line 327, in setupUi
    self.frame = QVTKRenderWindowInteractor(Form)
  File "C:\Users\djibi\Miniconda2\lib\site-packages\vtk\qt\QVTKRenderWindowInteractor.py", line 233, in __init__
    QWidget.__init__(self, parent, wflags | Qt.MSWindowsOwnDC)
TypeError: 'PySide.QtGui.QWidget' called with wrong argument types:
  PySide.QtGui.QWidget(MultiFrameDicomViewer, WindowFlags)
Supported signatures:
  PySide.QtGui.QWidget(PySide.QtGui.QWidget = None, PySide.QtCore.Qt.WindowFlags = 0)`

Any tips ? Thx

**Comment by dijbi** [comment]
I uninstall PySlide, modified  lib\site-packages\vtk\qt4\QVTKRenderWindowInteractor.py" to force the use of PyQT5 



```
import vtk.qt
try:
    import PyQt5
    vtk.qt.PyQtImpl = "PyQt5"
except ImportError:
    try:
        import PySide
        vtk.qt.PyQtImpl = "PySide"
    except ImportError:
        raise ImportError("Cannot load either PyQt or PySide")

from vtk.qt.QVTKRenderWindowInteractor import *

if __name__ == "__main__":
    print(PyQtImpl)
    QVTKRenderWidgetConeExample()
```


ICMA is launching (hooray). I can read a ACUSON 2000 DICOM, but the image shows up as one line....


![Capture](https://user-images.githubusercontent.com/42296521/55243994-956f6180-5240-11e9-9110-e64a4e13fa77.PNG).


I have see in pydicom issues section that two packages were needed to decompress compressed DICOM.
Can someone confirm if it is possible ? 

Thx

**Comment by Jagirhussan** [comment]
Thanks for your heroic efforts and persistence.
I have done a fresh install of miniconda 2.7 on windows, installed the required packages and run the application.
Below is the sequence of package installation commands

conda install pyqt=5
conda install scipy pandas requests opencv matplotlib pillow xlswriter
conda install -c clinicalgraphics pydicom gdcm
#Downloaded VTK‑7.1.1‑cp27‑cp27m‑win_amd64.whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#vtk
pip install VTK-7.1.1-cp27-cp27m-win_amd64.whl

Linked to opencmiss i,e.  <IDIR>\lib\python2.7\Release\opencmiss.zinc via python path
and was able to execute the application, view dicoms and create models.

Screenshot of the app along with installed packages
![icmascwithdependencies](https://user-images.githubusercontent.com/3771328/55300923-8124a200-5496-11e9-81c5-405759641680.png)

**Comment by dijbi** [comment]
Thanks a lot, with almost the same package version, i succeeded to lauch the software.
I had to install diskcache.
FYI I uploaded studies with a lot of cine loops & still pictures and the app crashed.
then,  i extracted some (2 or 3) cine loops, and i was OK.
With a phillips Cx50 study, i still have some compression issue, do you think it will make the LV strain less accurate ? or totally wrong ?

Here are my logs when i opened  a Phillips Cx50 study :

`Traceback (most recent call last):
  File "C:\Users\***\Miniconda2\lib\site-packages\vtk\qt\QVTKRenderWindowIntera
ctor.py", line 435, in keyPressEvent
    key = str(ev.text())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 0:
ordinal not in range(128)`

what if i transcode the DICOM file w/ another codec ?
Thks for saving my hopes ! :1

**Comment by Jagirhussan** [comment]
I think the crashing may be due to memory issues. We rely on packages such as vtk, pydicom etc and would not be able to address these.
The error is thrown by QVTKRenderWindowInteractor and not by a dicom module. So I donot think that this is a compression issue. Speckle tracking on compressed dicom's is not recommended.
Since the errors that you are raising now are not related to the initial issue i.e. 'No module _context'. I am closing this issue as resolved.
Please log a different issue if you run into one.
