### ISSUE TITLE
No module _context #4

### ISSUE THREAD

**Issue by Alex030593** [ABI-Software-Laboratory/ICMA#4]
Hi , did all the steps from the readme, a few times , did 4 windows backups since everything gets messy after all instructions are completed but i still get the No module _context. changed the PYTHONPATH manually, tried from the : python setup.py install, altghough it executed path remained unchanged. Tried python 3.7 first , then at a second try with 2.7 tried running all from a new conda env , and although i've set the python=2.7, after installing packages and executing conda info i got python version given as  3.7 , though it wasnt installed, think it my be with the packages downloading sideway some things from 3.7. 
    After opened the icma. bat file through a notepad and saw : 
SET icmapath=%~dp0
set PYTHONPATH=%icmapath%;$PYTHONPATH
python icma\ICMA.py

and i cant understand whats the point in putting a PYTHONPATH before running the program if it sets on its own when just starting the .bat. 

I was just wondering , if before setting the things with running the program the files should be somehow in a same folder or somehow combined , cause i get the feeling that it is checking the presence of folders in asingle path though these are different folders.
   Btw when installing miniconda it asks me if i am to set it as the main python for the windows, could it be the cause for the issue ?
    Tried at least 3 versions of OpenCMISS , dont think that would be the cause , more like because i cant set well the paths. Would be thankful for any help

**Comment by Jagirhussan** [comment]
Hi,
   OpenCMISS libraries are not supported on python 3.7, you will need python 3.6 (as stated in the Readme). 
   The ICMA modules are not installed in host python, however, they need to be loaded for the Software to work, setting the location of these modules in the PYTHONPATH will allow the interpreter to find these modules.
   Miniconda does not need to be the main python for windows.

**Comment by Alex030593** [comment]
So i cant understand whats the point of setting pythonpath to zinc directory since when executing icma .bat it has the instruction  set PYTHONPATH=%icmapath%;$PYTHONPATH which changes the pythonpath to the directory where icma.bat is (checked with echo %PYTHONPATH% before and after every run) , thats why not finging context module .
after i edit the icma.bat with a notepad setting the pythonpath to opencmiss.zinc directory (instead of =%icmapath%) i get the no icma module error.
i know i m doing something wrong with the paths but still cant understand what.
How do i set the pythonpath corectly since set command before running is useless?
Another thing is that opening python from conda env gives me python 3.6 while opening it from simple cmd i get python 3.7.
Btw can i contact you through some whatsapp/skype/fb to talk about the instalation?

**Comment by Jagirhussan** [comment]
Hi,
   There was an error in the bat file's set command. Apologies. 
It should be 'set PYTHONPATH=%icmapath%;%PYTHONPATH%' and not 'set PYTHONPATH=%icmapath%;$PYTHONPATH'. The code base has now been updated to reflect this. This will ensure that the new PYTHONPATH contains the existing definitions in its suffix.

With regards to having python 3.6, it may be that you have both 3.6 and 3.7 installed on your system. If you can activate python 3.6 environment from command line for instance by issuing 
> activate python.3.6 
where 'python3.6' is the environment name.
then you can set the environment in the bat file before launching. The updated bat file will be as follows

call activate python3.6
SET icmapath=%~dp0
set PYTHONPATH=%icmapath%;%PYTHONPATH%
python icma\ICMA.py

If you think you have only one instance of python installed on your system, you can download miniconda distribution which ships only python 3.6, latest versions ship python 3.7, a binary with python 3.6 is available at  https://repo.continuum.io/miniconda/Miniconda3-4.3.31-Windows-x86_64.exe

Hope that helps.

**Comment by Alex030593** [comment]
got it, thx for your time explaining. anyways , after a windows backup today while a new install figured out some things :
1. conda install scipy pandas requests opencv matplotlib pillow xlswriter- does not work, idk why , works only installing xlswriter apart, and the rest apart, but , while running  "conda install scipy pandas requests opencv matplotlib pillow" in a moment it begins downloading python 3.7 , this it how it got installed previous time , managed to exit the prompt while it was downloading and do the pip install for the rest apart (after getting errors like no scipy found ) , in order not to get the 3.7 installed.
   looking at the code error figured out that it was searching for the context directory in the miniconda lib so just manually threw the libs from opencmiss to miniconda 2 lib directory , after all the application ran but : 
2. while getting the US images to the program all of them where green tinted (found same bug in other dicom readers) , solved this by uploading them to microdicom, then exporting as dicom series ,then getting them again to ICMA,things worked, overall might be because of the method a US machine compresses the dicom images before exporting ,idk
3. Finally tried to get a speckle tracking made but figured out that image analysis is pretty poor even though the images were good (mostly bec bottom pointers where getting in the first few slides the opened mitral valve as part of the septum and jumping from the walls to the cusps). 
 Anyways thx for your time and to the people working on this, guess the issue can be closed
